### ISSUE TITLE
Document hidden functionality

### ISSUE THREAD

**Issue by alexstanbury** [g4rcez/brouther#25]
This router looks interesting, I noticed there seems to be some kind of loader ability for the routes, as well as some other hooks, is there a reason these aren't documented?

**Comment by g4rcez** [comment]
I'm doing the documents about loader and actions at #26 . You can check the PR and suggest situations. I will take your suggestions and create examples with these.

**Comment by g4rcez** [comment]
@alexstanbury you can check the docs on https://brouther.vercel.app/form
