### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [g4rcez/brouther#6]
[The Router Challenge](https://github.com/grahammendick/router-challenge) aims to be to Routers what TodoMVC was to MV* frameworks. It offers the same Music Catalog application built in React using different Routers. For it to be successful I need the help of Router writers like you. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the Music Catalog application using brouther, please?

**Comment by g4rcez** [comment]
I'm not able to do this at this time. You can see an implementation of brouther [here](https://github.com/g4rcez/brouther/tree/main/playground) and do your own implementation for the Router Challenge
